spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER}
elastic:
  host: ${ELASTIC_HOSTS}
  fingerprint: ${ELASTIC_CERT_FINGERPRINT}
  apikey: ${ELASTIC_API_KEY}