okta:
  oauth2:
    issuer:${ISSUER}
spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
  jooq:
    sql-dialect: